### ISSUE TITLE
错误反馈

### ISSUE THREAD

**Issue by fuqiang03** [505575853/lede1#1]
![qq 20181013121357](https://user-images.githubusercontent.com/26851715/46901294-7de72b00-cee3-11e8-8d07-77a85c437a0d.png)
![qq 20181013121415](https://user-images.githubusercontent.com/26851715/46901295-7e7fc180-cee3-11e8-8482-2c7cbf9ba8be.png)
自动更新不先上的话  无法保存设置

**Comment by 505575853** [comment]
以修改
