### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by fuqiang03** [505575853/lede1#2]
pdnds错误还是chuian出现了
bbr也出现了小错误
bbr最好分版本判断启动  不要和魔改的原版的一起卸载模块 控制页面有一个启动开关就足够了
S99dnsforwarder: line 192: syntax error: unexpected end of file (expecting "}")  无法启动了，还有这个/var/etc/dnsmasq-go.d 提示文件不存在求解
![qq 20181015200818](https://user-images.githubusercontent.com/26851715/46950182-7deb5480-d0b6-11e8-8862-22cacb81de42.png)
![qq 20181015201049](https://user-images.githubusercontent.com/26851715/46950184-7e83eb00-d0b6-11e8-8e72-8090fa95bcf9.png)
无法看到网络邻居的里面电脑了 求大神帮助 求解决思路或者办法 以前貌似跟mwan3 有关来的 现在不知道更新了什么 

![qq 20181015202736](https://user-images.githubusercontent.com/26851715/46951033-4f22ad80-d0b9-11e8-8af9-8ba6f4ae7f3c.png)

**Comment by 505575853** [comment]
我已经转用lean大源码你可以用他的源码编译

**Comment by fuqiang03** [comment]
大神的插件还是不错的兼容性很强

**Comment by fuqiang03** [comment]
我只用的他的4个插件 问题也不少
